// https://www.lipsum.com/feed/html
// as a JS file 'cause webpack JSON importing won't work for me
module.exports = ` Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc dictum, eros et vehicula pretium, sem est varius turpis, eu molestie lorem purus vel lectus. Sed blandit massa ex, scelerisque volutpat diam tristique in. Quisque sem eros, sollicitudin at aliquam quis, ultricies id sapien. Etiam non suscipit risus. Cras posuere ex a erat ultricies tristique. Cras vestibulum ex non commodo aliquam. In purus leo, faucibus eu est eget, vulputate pulvinar mauris. Nunc nec sapien vel ante maximus pretium sed non nisi. Donec rutrum erat erat, non posuere neque mollis vel. Etiam tristique volutpat orci, quis finibus metus sodales eu.

Suspendisse eleifend varius ultrices. Nullam dui metus, cursus vel quam vitae, fringilla scelerisque urna. Aenean lobortis eros leo. Vivamus vel lectus sit amet ante vulputate imperdiet. Nam ac euismod dolor. Ut sollicitudin varius eros sit amet malesuada. In venenatis purus nec odio efficitur consectetur. Integer tristique enim et dui vestibulum, ac placerat purus pharetra. Fusce euismod vitae justo at vulputate. Duis maximus leo nec ex vehicula, ac rutrum eros scelerisque. Praesent nec libero vel lacus pretium sollicitudin quis a sem. Nulla sit amet suscipit enim, a elementum augue. Pellentesque eget malesuada enim. Cras consequat libero metus.

Maecenas ultricies nisi ut tortor aliquet, at porttitor nibh mollis. Cras pellentesque quam ut augue sagittis tempor. Nam aliquam eu nisi sit amet pharetra. Aenean sit amet finibus nunc. Quisque at arcu sapien. Donec eu enim ornare, convallis ex a, tristique sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pellentesque pharetra sollicitudin.

Vivamus viverra imperdiet sem ac vestibulum. In fringilla malesuada augue. Pellentesque tempus erat nec libero tincidunt scelerisque. Mauris aliquet dignissim neque vel dignissim. Fusce consequat porttitor dapibus. Quisque accumsan lacus nec metus mollis convallis. Aenean metus felis, vulputate sit amet nibh ac, iaculis pellentesque est. Pellentesque id tortor eu nisl vehicula maximus vitae at ipsum. Donec in orci lorem. Donec viverra malesuada pellentesque. Donec vitae nulla eget nisi convallis tristique. Aenean placerat, dui ac tempus sagittis, quam dolor rutrum orci, ac vulputate urna arcu non tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed viverra justo eget ligula imperdiet fermentum. In a turpis arcu.

Sed eget vulputate leo. Integer vitae porta turpis. Curabitur sit amet mi malesuada, tincidunt ligula sed, maximus tortor. Sed bibendum id lectus sed sodales. Pellentesque nec purus ut mi tincidunt venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur consectetur arcu vel velit eleifend, a mollis lectus luctus. Pellentesque et pulvinar ipsum. Etiam eu porta sem, id imperdiet velit. Aenean sodales dui in neque cursus, et fermentum nunc bibendum. Aliquam et augue sed justo pulvinar finibus ut eu leo. Vivamus ac odio rutrum, fringilla ante vel, interdum ligula. Phasellus imperdiet et mi et efficitur. Quisque quam sapien, finibus id tincidunt quis, scelerisque id purus. Vivamus rhoncus ex in purus sagittis vestibulum.

Maecenas consectetur, purus et interdum vulputate, justo ipsum sagittis dui, sit amet volutpat lacus quam in dui. Mauris quis elit dolor. Etiam vitae rutrum diam. Nunc nec aliquam nibh. Donec ac urna consectetur diam vestibulum dignissim eu non massa. Quisque at venenatis enim, ut tristique felis. Nam nibh neque, sagittis id iaculis vel, rutrum id ligula. In vel tempus risus, at ornare elit. Nullam velit lorem, tristique id ex nec, accumsan luctus elit. Vestibulum tincidunt magna eu convallis vestibulum. Duis sapien sem, egestas id leo sed, condimentum sagittis ex. Vestibulum dapibus orci vel laoreet placerat. Etiam posuere nulla eget quam tincidunt facilisis.

Nullam volutpat purus massa, ut ullamcorper sem dignissim ut. Aliquam dignissim cursus euismod. Nam nec dolor euismod, sagittis lectus eu, pellentesque tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque pretium tincidunt sapien in tristique. Nunc non erat turpis. Morbi eget venenatis est, et ornare sem. Aenean egestas molestie quam sed finibus. Cras egestas lacinia pellentesque. Etiam vitae tincidunt libero, in laoreet ligula. Integer augue quam, ultricies eget euismod eget, ultricies non eros. Nulla consectetur vehicula ante, sit amet laoreet lacus accumsan ac. Sed sollicitudin libero turpis, vitae malesuada nisi tristique eu. Aliquam et pretium urna. Proin fermentum nisl sit amet nunc lobortis malesuada.

Integer quis urna sit amet nulla fermentum lobortis vulputate eget nulla. Nunc interdum quam at ultrices consequat. Vivamus vel leo id mi malesuada scelerisque. Etiam tincidunt eros ac quam scelerisque faucibus. Quisque efficitur orci sed erat rhoncus bibendum. Integer mi lacus, pretium et semper vitae, maximus nec justo. Maecenas commodo ullamcorper diam, quis egestas risus commodo nec.

Nullam quis est nisi. Pellentesque aliquam quis nisi vel eleifend. Sed nec mollis risus. Etiam nibh justo, egestas in nisl sed, euismod lobortis purus. Ut a commodo magna. Cras maximus mauris consequat lectus eleifend placerat. Sed lectus elit, posuere pellentesque lectus pharetra, venenatis rutrum nunc. Donec vel aliquam sapien. Pellentesque sit amet pulvinar purus. Fusce at odio vitae quam pretium hendrerit. Nulla pretium, sapien quis dapibus vehicula, lorem sem molestie felis, id dignissim erat lorem nec ligula. Donec ultrices ante nunc, vitae porta lectus aliquam ultricies. Donec ultricies consequat massa, quis hendrerit lectus tempus ut.

Curabitur faucibus lectus vitae lorem convallis, sit amet consequat nisi aliquet. Vestibulum commodo molestie quam, eu laoreet est egestas vel. Duis placerat ac quam ut feugiat. Morbi massa tellus, semper placerat elit at, convallis vestibulum nisi. Fusce commodo molestie fringilla. Nullam sagittis eu mi a faucibus. In accumsan ante quis accumsan sodales.

Fusce lacinia purus non felis feugiat commodo. Sed sollicitudin libero sed ligula scelerisque, non gravida lorem semper. In fringilla, ante vel semper tincidunt, magna velit aliquam nisi, id lobortis nisi magna eget metus. Ut odio metus, lacinia et dictum quis, cursus id nulla. Aliquam efficitur justo sit amet volutpat placerat. Morbi mauris eros, blandit vel dignissim in, accumsan ac quam. Aliquam malesuada ex ac felis ullamcorper, vitae dignissim turpis scelerisque. Maecenas non mi et felis viverra semper. Praesent at elementum lacus. Quisque suscipit ligula sapien, eu facilisis augue egestas vitae. Mauris eu est viverra, auctor nisl in, tincidunt diam.

Nam dictum varius convallis. Duis sed varius nulla. Morbi aliquet vehicula arcu ac hendrerit. Sed in nulla luctus, auctor lectus auctor, tempus dolor. Proin eget hendrerit tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a erat euismod, cursus sapien nec, auctor lacus. In hac habitasse platea dictumst. Phasellus congue neque eget justo vulputate, vel rhoncus odio gravida. Integer porta sagittis sollicitudin. Morbi vitae tincidunt augue, nec fermentum mauris. Donec tortor dolor, sodales quis mauris sed, placerat aliquam orci. Proin mattis venenatis mollis. Aenean rhoncus ornare risus, at vehicula justo consequat sed. Donec vel egestas mi, et volutpat nisl. Fusce id orci nulla.

Aliquam laoreet maximus blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut ac mollis nisi, eu pretium lacus. Aenean eu mi lectus. Praesent aliquam elit nulla, ut blandit elit iaculis sed. Nullam est libero, congue ut urna eu, placerat lacinia neque. Nullam bibendum augue at lorem convallis pellentesque. Mauris convallis posuere finibus. Duis sed iaculis tortor, eget volutpat ante. In dictum augue at massa suscipit, a suscipit arcu vehicula. Nullam tincidunt sem vitae nisl tincidunt eleifend. Quisque pharetra odio augue, vel sollicitudin dui auctor ac.

Praesent interdum mauris at metus pretium elementum. In tellus leo, malesuada sed orci vitae, luctus vestibulum lectus. Nunc eget purus non est dictum vestibulum. Etiam sed dolor nisl. Maecenas sodales eget justo maximus commodo. Sed vulputate, urna vehicula auctor sagittis, enim nibh facilisis metus, et sodales est eros in neque. Vivamus dui orci, volutpat eget risus at, mollis sollicitudin lectus. Nulla in elit a neque ornare accumsan. Integer pellentesque ultricies purus, non malesuada massa mattis vitae. Etiam quis euismod augue. In commodo in augue sed congue. Sed ut porta velit. Cras at semper massa, mattis sollicitudin arcu. Nulla tempus ullamcorper euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam tincidunt id nunc ut tempus.

Nullam enim turpis, molestie vitae fringilla sed, rutrum commodo lectus. Curabitur facilisis justo lacus. Nulla facilisi. In gravida turpis et lorem imperdiet pretium. Proin ac tristique arcu. Nulla varius arcu nec est posuere, at eleifend nunc viverra. Nam vitae placerat tortor. Vivamus nec sapien auctor, auctor felis quis, rhoncus leo. Sed suscipit erat quis elit tempor pretium. Aenean euismod tortor a ante mattis, a molestie nisi finibus. Maecenas sed faucibus erat. Integer id leo ullamcorper, ultrices metus et, laoreet velit. Duis rhoncus varius sapien, et sodales augue lacinia vel. Nunc augue metus, condimentum a mi vitae, dignissim imperdiet enim. In sit amet justo auctor, tristique lacus ut, finibus leo.`